# Buildspec syntax
# https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - pip3 install -r requirements.txt
  build:
    commands:
      - python -m pytest --junitxml=pytest-reports/test.xml

reports:
  pytest_reports:
    files:
      - test.xml
    base-directory: pytest-reports
    file-format: JUNITXML
